; Generated by tools/make_tables.py - do not edit.

; ---- MZ-800 colours 0-15 for the Bt476 (R, G, B, 6 bits each)
mz_colours:
	defb 00h,00h,00h		; 0
	defb 10h,10h,2Bh		; 1
	defb 34h,0Dh,00h		; 2
	defb 2Dh,03h,23h		; 3
	defb 10h,1Bh,00h		; 4
	defb 09h,33h,3Fh		; 5
	defb 3Ah,35h,0Ch		; 6
	defb 34h,34h,34h		; 7
	defb 21h,21h,21h		; 8
	defb 00h,23h,3Ah		; 9
	defb 3Fh,00h,00h		; 10
	defb 3Ch,15h,33h		; 11
	defb 15h,3Fh,15h		; 12
	defb 20h,3Fh,3Fh		; 13
	defb 3Fh,3Fh,0Ah		; 14
	defb 3Fh,3Fh,3Fh		; 15
