; Generated by tools/make_tables.py - do not edit.

; ---- pixel conversion, four pages (see make_tables.py)
pix_lo1:
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
	defb 00h,80h,40h,0C0h,20h,0A0h,60h,0E0h,10h,90h,50h,0D0h,30h,0B0h,70h,0F0h
pix_hi1:
	defb 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
	defb 80h,80h,80h,80h,80h,80h,80h,80h,80h,80h,80h,80h,80h,80h,80h,80h
	defb 40h,40h,40h,40h,40h,40h,40h,40h,40h,40h,40h,40h,40h,40h,40h,40h
	defb 0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h
	defb 20h,20h,20h,20h,20h,20h,20h,20h,20h,20h,20h,20h,20h,20h,20h,20h
	defb 0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h,0A0h
	defb 60h,60h,60h,60h,60h,60h,60h,60h,60h,60h,60h,60h,60h,60h,60h,60h
	defb 0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h
	defb 10h,10h,10h,10h,10h,10h,10h,10h,10h,10h,10h,10h,10h,10h,10h,10h
	defb 90h,90h,90h,90h,90h,90h,90h,90h,90h,90h,90h,90h,90h,90h,90h,90h
	defb 50h,50h,50h,50h,50h,50h,50h,50h,50h,50h,50h,50h,50h,50h,50h,50h
	defb 0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h,0D0h
	defb 30h,30h,30h,30h,30h,30h,30h,30h,30h,30h,30h,30h,30h,30h,30h,30h
	defb 0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h,0B0h
	defb 70h,70h,70h,70h,70h,70h,70h,70h,70h,70h,70h,70h,70h,70h,70h,70h
	defb 0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h
pix_lo2:
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
	defb 00h,08h,04h,0Ch,02h,0Ah,06h,0Eh,01h,09h,05h,0Dh,03h,0Bh,07h,0Fh
pix_hi2:
	defb 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
	defb 08h,08h,08h,08h,08h,08h,08h,08h,08h,08h,08h,08h,08h,08h,08h,08h
	defb 04h,04h,04h,04h,04h,04h,04h,04h,04h,04h,04h,04h,04h,04h,04h,04h
	defb 0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch,0Ch
	defb 02h,02h,02h,02h,02h,02h,02h,02h,02h,02h,02h,02h,02h,02h,02h,02h
	defb 0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah,0Ah
	defb 06h,06h,06h,06h,06h,06h,06h,06h,06h,06h,06h,06h,06h,06h,06h,06h
	defb 0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh,0Eh
	defb 01h,01h,01h,01h,01h,01h,01h,01h,01h,01h,01h,01h,01h,01h,01h,01h
	defb 09h,09h,09h,09h,09h,09h,09h,09h,09h,09h,09h,09h,09h,09h,09h,09h
	defb 05h,05h,05h,05h,05h,05h,05h,05h,05h,05h,05h,05h,05h,05h,05h,05h
	defb 0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh,0Dh
	defb 03h,03h,03h,03h,03h,03h,03h,03h,03h,03h,03h,03h,03h,03h,03h,03h
	defb 0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh,0Bh
	defb 07h,07h,07h,07h,07h,07h,07h,07h,07h,07h,07h,07h,07h,07h,07h,07h
	defb 0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh,0Fh
