#!/usr/bin/env python3
"""Generate sapi/tables.asm (pixel conversion MZ-800 -> CGA-1V) and sapi/colours.asm (palette).

MZ-800 320x200 / 4 colours: two planes, one byte = 8 pixels, bit 0 = left pixel.
CGA-1V CGA mode: one byte = 4 pixels, high nibble = plane I (D7 left),
low nibble = plane II. One MZ byte -> two CGA bytes (pixels 0-3, 4-7).

  pix_lo1[b]  pixels 0-3 of b as plane I  (high nibble of CGA byte 0)
  pix_hi1[b]  pixels 4-7 of b as plane I  (high nibble of CGA byte 1)
  pix_lo2[b]  pixels 0-3 of b as plane II (low nibble of CGA byte 0)
  pix_hi2[b]  pixels 4-7 of b as plane II (low nibble of CGA byte 1)
The four tables are consecutive pages in this order (tables.asm is
included at a page boundary).
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

# mz800emu palette of the 16 MZ-800 colours (IGRB), measured from its screenshots
MZ_RGB = [(0, 0, 0), (64, 64, 172), (208, 52, 0), (180, 12, 140), (64, 108, 0), (36, 204, 255),
          (232, 212, 48), (208, 208, 208), (132, 132, 132), (0, 140, 232), (255, 0, 0), (240, 84, 204),
          (84, 255, 84), (128, 255, 255), (255, 255, 40), (255, 255, 255)]


def rev8(b):
    return int('{:08b}'.format(b)[::-1], 2)


def hx(v):
    s = '%02X' % v
    return ('0' + s if s[0] in 'ABCDEF' else s) + 'h'


def table(name, f, out):
    out.append('%s:' % name)
    vals = [f(b) for b in range(256)]
    for i in range(0, 256, 16):
        out.append('\tdefb ' + ','.join(hx(v) for v in vals[i:i + 16]))


def main():
    out = ['; Generated by tools/make_tables.py - do not edit.', '']
    out.append('; ---- pixel conversion, four pages (see make_tables.py)')
    table('pix_lo1', lambda b: rev8(b) & 0xF0, out)
    table('pix_hi1', lambda b: (rev8(b) << 4) & 0xF0, out)
    table('pix_lo2', lambda b: rev8(b) >> 4, out)
    table('pix_hi2', lambda b: rev8(b) & 0x0F, out)
    open(os.path.join(ROOT, 'sapi', 'tables.asm'), 'w', newline='\n').write('\n'.join(out) + '\n')
    out = ['; Generated by tools/make_tables.py - do not edit.', '',
           '; ---- MZ-800 colours 0-15 for the Bt476 (R, G, B, 6 bits each)', 'mz_colours:']
    for i, (r, g, b) in enumerate(MZ_RGB):
        out.append('\tdefb %s,%s,%s\t\t; %d' % (hx(r >> 2), hx(g >> 2), hx(b >> 2), i))
    open(os.path.join(ROOT, 'sapi', 'colours.asm'), 'w', newline='\n').write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
